from admet.core.schema import Param, ParamKind, ParamSchema
from admet.core.workflow import Stage, StageControl, Workflow


def create_analyze_workflow() -> Workflow:
    return Workflow(
        workflow_id="analyze",
        label="Analysis",
        stages=(
            Stage(
                "import",
                "1. Import data",
                description="Select videos, image folders, or batch manifests for analysis.",
                instructions=(
                    "Choose a video for OpenCV analysis or an image directory for Cellpose analysis.",
                    "Use the batch area to collect files before running a multi-sample pass.",
                ),
                settings=ParamSchema(
                    (
                        Param("video_path", "Video Path", ParamKind.PATH, default=""),
                        Param("input_dir", "Image Directory", ParamKind.PATH, default=""),
                        Param("batch_dir", "Batch Directory", ParamKind.PATH, default=""),
                        Param("output_dir", "Output Directory", ParamKind.PATH, default="output"),
                    )
                ),
                controls=(StageControl("Import Ready", completes=True, variant="success"),),
            ),
            Stage(
                "matrix",
                "2. Batch matrix",
                description="Review sample identifiers and per-sample settings before execution.",
                instructions=(
                    "Confirm one row per sample.",
                    "Keep engine-specific paths and output locations stable before starting analysis.",
                ),
                settings=ParamSchema(
                    (
                        Param("sample_id", "Sample ID", ParamKind.TEXT, default="demo"),
                        Param("config_path", "Config Path", ParamKind.PATH, default=""),
                    )
                ),
                controls=(StageControl("Matrix Ready", completes=True, variant="success"),),
            ),
            Stage(
                "analyze",
                "3. Analyze",
                action="analyze",
                description="Run the selected engine and stream results into the table and plots.",
                settings=ParamSchema(
                    (
                        Param("microns_per_pixel", "Microns Per Pixel", ParamKind.FLOAT, default=1.0),
                        Param("px_to_um", "Pixels To Microns", ParamKind.FLOAT, default=1.14),
                        Param("fps", "FPS", ParamKind.FLOAT, default=0.0, minimum=0.0),
                        Param("max_frames", "Max Frames", ParamKind.INTEGER, default=None),
                        Param("frame_limit", "Frame Limit", ParamKind.INTEGER, default=None),
                        Param("use_cache", "Use Cache", ParamKind.BOOLEAN, default=True),
                        Param("detect_inclusions", "Detect Inclusions", ParamKind.BOOLEAN, default=True),
                        Param("write_artifacts", "Write Artifacts", ParamKind.BOOLEAN, default=True),
                    )
                ),
                controls=(StageControl("Run Analysis", "analyze", completes=True),),
            ),
            Stage(
                "view",
                "4. View",
                description="Inspect result tables, summary statistics, and plots.",
                instructions=(
                    "Use summary statistics for pass/fail checks.",
                    "Use records for droplet-level and track-level diagnostics.",
                ),
                controls=(StageControl("Review Done", completes=True, variant="success"),),
            ),
            Stage(
                "export",
                "5. Export",
                skippable=True,
                description="Export artifacts generated by the active analysis engine.",
                settings=ParamSchema(
                    (
                        Param("export_dir", "Export Directory", ParamKind.PATH, default="exports"),
                    )
                ),
                controls=(
                    StageControl("Skip Export", skippable=True, variant="secondary"),
                    StageControl("Export Done", completes=True, variant="success"),
                ),
            ),
        ),
    )
